server:
  port: 8999

spring:
  datasource:
    url: jdbc:postgresql://localhost:3307/microservice
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  instance:
    prefer-id-address: true
  client:
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info, health