server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-id-address: true
  client:
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
          include: info, health
